Stat svc
DanielSJavaDev/java-explore-with-me pull request #4
Opened 2023-02-22 19:56 UTC by DanielSJavaDev

2023-02-23 04:21 UTC, krylov-sergey-sergeevich requested changes
**Привет**

Есть некоторые вопросы, что-то в коде отметил сразу
1) Не заметил http клиент для работы с модулем статистики
2) Что думаешь быть на счет еще одной таблицы в БД  с названием примерно apps где мы бы хранили название например и из таблицы с hit ссылались бы на app при помощи foreign key?

3) **Можно лучше:** докинуть логгирование где оно было бы уместно

**Вопрос по:** "Определится с тематикой дополнительной функциональности, которую вы будете реализовывать" **какой она будет?**

Буду ждать  с правками, если что пиши в пачке =)

2023-02-23 04:21 UTC, krylov-sergey-sergeevich commented on ewm-service/pom.xml
> +            <version>1.18.24</version>
Версию давай вынесем в properties блок

2023-02-23 04:21 UTC, krylov-sergey-sergeevich commented on stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +public class StatsController {
Давай докинем логгирование сюда

2023-02-23 04:21 UTC, krylov-sergey-sergeevich commented on stats-server/src/main/java/ru/practicum/dto/HitDto.java
> +public class HitDto {
Модификаторы доступа

2023-02-23 04:21 UTC, krylov-sergey-sergeevich commented on stats-server/src/main/java/ru/practicum/dto/ViewStats.java
> +public class ViewStats {
Модификаторы доступа

2023-02-23 04:21 UTC, krylov-sergey-sergeevich commented on stats-server/src/main/java/ru/practicum/model/Hit.java
> +public class Hit {
Модификаторы доступа

2023-02-23 04:21 UTC, krylov-sergey-sergeevich commented on stats-server/src/main/java/ru/practicum/service/HitMapper.java
> +    public static Hit toHit(HitDto hitDto) {
**Стиль:** Пустую строку между объявлением класса и методом

2023-02-24 14:37 UTC, DanielSJavaDev commented
Привет! По замечаниям всё исправил, клиент добавил, логирование добавил. По поводу ещё одной таблицы думаю, что это можно сделать, но на рефакторинге, если успею. Времени очень мало осталось, а работы ещё очень много по второй части.
Доп функциональность взял бы рейтинги, как раз недавно реализовывал, не займёт много времени

2023-02-26 14:03 UTC, closed without merging

2023-02-26 14:03 UTC, DanielSJavaDev commented
Не могу сюда запушить, структуру менял много раз, открою новый реквест