feat: main service first
DanielSJavaDev/java-explore-with-me pull request #6
Opened 2023-03-01 17:44 UTC by DanielSJavaDev

2023-03-02 06:52 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохая работа - отметил что можно улучшить и пару вопросов задал

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/pom.xml
> +        <dependency>
Для чего эту зависимость добавили?

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +    email VARCHAR(128) NOT NULL UNIQUE
Можно лучше:
CONSTRAINT pk_user PRIMARY KEY (id),
CONSTRAINT UQ_USER_EMAIL UNIQUE (email)

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +    name VARCHAR(128) NOT NULL UNIQUE
Можно лучше:
CONSTRAINT pk_categories PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +    views              BIGINT
Можно лучше:
CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT FK_EVENTS_ON_CAT FOREIGN KEY (cat_id) REFERENCES categories (id),
  CONSTRAINT FK_EVENTS_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id)

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +    pinned BOOL         NOT NULL
CONSTRAINT pk_compilation PRIMARY KEY (id)

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +    PRIMARY KEY (event_id, compilation_id)
CONSTRAINT pk_compilation_of_events PRIMARY KEY (comp_id, event_id),
  CONSTRAINT fk_comofeve_on_compilation FOREIGN KEY (comp_id) REFERENCES compilations (id),
  CONSTRAINT fk_comofeve_on_event FOREIGN KEY (event_id) REFERENCES events (id)

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +    UNIQUE (event_id, requester_id)
CONSTRAINT pk_participation_requests PRIMARY KEY (id),
  CONSTRAINT FK_PARTICIPATION_REQUESTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id),
  CONSTRAINT FK_PARTICIPATION_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id),
  CONSTRAINT UQ_PARTICIPANT_PER_EVENT UNIQUE (requester_id, event_id)

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on stats-service/client/pom.xml
> +            <artifactId>dto</artifactId>
Это что за зависимость?

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on stats-service/pom.xml
> +        <module>dto</module>
Зачем отдельный модуль?

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/config/HitClientConfig.java
> +    HitClient hitClient() {
public

2023-03-02 06:52 UTC, krylov-sergey-sergeevich commented on ewm-service/pom.xml
> +            <version>6.2.5.Final</version>
а srping-validator не хватает?

2023-03-03 14:52 UTC, DanielSJavaDev commented on ewm-service/pom.xml
> +        <dependency>
Без зависимости не собирался проект, вылетала ошибка на импорты, разделение стат сервиса на подмодули и добавление зависимостей эту проблему решили

2023-03-03 14:53 UTC, DanielSJavaDev commented on stats-service/client/pom.xml
> +            <artifactId>dto</artifactId>
Выше описал ситуацию

2023-03-03 14:53 UTC, DanielSJavaDev commented on stats-service/pom.xml
> +        <module>dto</module>
Выше описал

2023-03-03 15:05 UTC, DanielSJavaDev commented on ewm-service/pom.xml
> +            <version>6.2.5.Final</version>
Хватает)) Возможно случайно идея добавила

2023-03-03 15:57 UTC, DanielSJavaDev commented
Привет! На вопросы ответил, по замечаниям всё исправил, в логике ничего не менял, но проверка падает)) Я уже начал писать доп фичу в новом репо и не смогу сюда перепушить тоже самое, можно мне по правкам зачёт поставить, и я эту ветку смёржу как есть.

2023-03-03 16:00 UTC, DanielSJavaDev commented
Иначе придётся отсюда клонировать мейн, из нового проекта всё в него переносить, заново всё собирать-разворачивать и пытаться все эти проверки заново проходить))) Два дня до дедлайна, вообще не до этого сейчас...

2023-03-03 21:36 UTC, DanielSJavaDev commented
Привет! На вопросы ответил, по замечаниям всё исправил. Нашёл в логах проблему: ERROR: multiple primary keys for table "users" are not allowed, уже исправил, но в этот реквест не смогу запушить потому, что начал писать доп фичу в новом репо.

2023-03-04 07:34 UTC, krylov-sergey-sergeevich commented
Напиши мне пожалуйста в пачке.
Надо понять почему 1 из проверок не проходит, без нее зачесть не получится

2023-03-04 09:20 UTC, krylov-sergey-sergeevich requested changes
Привет, вижу правки и видел сообщение, но смогу зачесть когда будут обе проверки пройдены на гитхабе. Если что пиши в пачке =)

2023-03-04 12:21 UTC, closed without merging