feat: add event rating feature
DanielSJavaDev/java-explore-with-me pull request #8
Opened 2023-03-05 20:55 UTC by DanielSJavaDev

2023-03-06 00:31 UTC, DanielSJavaDev commented
Привет! Всё работает, но скорее всего неправильно)) Сдаю, чтобы уложиться в дедлайн, по замечаниям буду доделывать

2023-03-06 15:35 UTC, DanielSJavaDev commented
в мейне в readme добавил ссылку вместо этой ветки

2023-03-07 14:59 UTC, krylov-sergey-sergeevich requested changes
Привет

1. Почему кажется что неверно сделано?)
2. Немного запутался я, ветка называется feature_rating_events те мы должны функционал с рейтингом делать а вижу голоса, а рейтинг не вижу


Буду ждать с правками и если что пиши в пачке, обсудим =)

2023-03-07 14:59 UTC, krylov-sergey-sergeevich commented on README.md
> +Front view example for rating feature:
Описание скромное, давай с душой оформим, что изменилось и в чем фича состоялась

2023-03-07 14:59 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/Vote.java
> +public class Vote {
Если я правильно понял то это рейтинг на самом деле, тогда лучше назвать наверно Rate

2023-03-07 14:59 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/Vote.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Вот эта штука мне не оч нравится, я приверженец руками написать private / private final - но тут дело ваше)

2023-03-07 14:59 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/repository/EventRepository.java
> +    @Query(value = "select * from events order by random() limit 1", nativeQuery = true)
Можно пояснить в чем суть запроса?

2023-03-07 14:59 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/service/RatingService.java
> +    LinkedList<EventShortDto> getRating(boolean isRandom, boolean isAsc, String type, Integer from, Integer size);
Почему LinkedList

2023-03-07 14:59 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/service/RatingService.java
> +    void setViews(Long id);
Не оч название метода и переменной и суть из-за этого не ясна

2023-03-08 10:19 UTC, DanielSJavaDev commented on ewm-service/src/main/java/ru/practicum/ewm/repository/EventRepository.java
> +    @Query(value = "select * from events order by random() limit 1", nativeQuery = true)
Да, суть в том, что пользователь может запросить рейтинг ивентов либо с рандомным ивентом в начале списка, либо без него, это запрос на рандомный ивент из таблицы

2023-03-08 10:24 UTC, DanielSJavaDev commented
Привет, суть фичи в составлении рейтинга событий на основе голосов пользователей(Vote) и вывода рейтинга на фронте в виде списка, визуальный пример добавил в ридми, описание добавлю. Неверно сделаны запросы к бд на рейтинги, а слабые постман тесты это не улавливают, но если будет много ивентов, всё посыпется)) Исправлю это и отправлю новую версию

2023-03-08 10:26 UTC, DanielSJavaDev commented
Вообще может я не правильно понял суть фичи и рейтинг не связан с лайками/дизлайками, а формируется на основе просмотров, подумаю над этим, может чуть переделаю

2023-03-08 11:35 UTC, DanielSJavaDev commented on ewm-service/src/main/java/ru/practicum/ewm/service/RatingService.java
> +    LinkedList<EventShortDto> getRating(boolean isRandom, boolean isAsc, String type, Integer from, Integer size);
Для формирования рейтинга asc или desc и добавление рандомного события в начало списка.

2023-03-08 12:22 UTC, closed without merging